# Generated by Django 4.2.3 on 2023-07-22 10:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Daily_add_model_demo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type_choose",
                    models.CharField(
                        choices=[("income", "INCOME"), ("expense", "EXPENSE")],
                        default="cash",
                        max_length=20,
                    ),
                ),
                ("component", models.CharField(max_length=100)),
                ("amount", models.FloatField(max_length=100)),
                ("date", models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
