# Generated by Django 3.2.6 on 2023-07-19 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('adress', models.CharField(default='', max_length=100)),
                ('country', models.CharField(default='', max_length=100)),
                ('postal_code', models.IntegerField(default=0, max_length=100)),
                ('phoneNumber', models.IntegerField(default=0)),
            ],
        ),
    ]
